### ISSUE TITLE
EROR] (cssharp:Core) 

### ISSUE THREAD

**Issue by asdfxD** [Dyshay/CS2Skin#1]
[EROR] (cssharp:Core) Could not load plugin "/home/container/game/csgo/addons/counterstrikesharp/plugins/CSSKin/CSSKin.dll"
System.InvalidOperationException: Dependency resolution failed for component /home/container/game/csgo/addons/counterstrikesharp/plugins/CSSKin/CSSKin.dll with error code -2147450734. Detailed error: Failed to locate managed application [/home/container/game/csgo/addons/counterstrikesharp/plugins/CSSKin/CSSKin.dll]

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at McMaster.NETCore.Plugins.Loader.ManagedLoadContext..ctor(String mainAssemblyPath, IReadOnlyDictionary`2 managedAssemblies, IReadOnlyDictionary`2 nativeLibraries, IReadOnlyCollection`1 privateAssemblies, IReadOnlyCollection`1 defaultAssemblies, IReadOnlyCollection`1 additionalProbingPaths, IReadOnlyCollection`1 resourceProbingPaths, AssemblyLoadContext defaultLoadContext, Boolean preferDefaultLoadContext, Boolean lazyLoadReferences, Boolean isCollectible, Boolean loadInMemory, Boolean shadowCopyNativeLibraries)
   at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.Build()
   at McMaster.NETCore.Plugins.PluginLoader..ctor(PluginConfig config)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Action`1 configure)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes, Action`1 configure)
   at CounterStrikeSharp.API.Core.Plugin.PluginContext..ctor(IServiceProvider applicationServiceProvider, IScriptHostConfiguration hostConfiguration, String path, Int32 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 62
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 50

**Comment by Dyshay** [comment]
Add me on Discord : https://discord.gg/HR44Y9UD

**Comment by dyshay** [comment]
I will upload new archive tomorrow
Something is wrong

**Comment by dyshay** [comment]
It's okay the correct package is available

**Comment by asdfxD** [comment]
thx for update. when using css_skin i get this

EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot Open when State is Open.
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 392
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 381
   at CSSKin.Core.Services.WeaponServerMysqlRepository.Get(String uuid) in C:\Users\dyl_c\RiderProjects\CSSKin\CSSKin\Core\Services\WeaponServerMysqlRepository.cs:line 47
   at CSSKin.CSSkin.OnCssSkinCommand(CCSPlayerController player, CommandInfo commandInfo) in C:\Users\dyl_c\RiderProjects\CSSKin\CSSKin\CSSkin.cs:line 250
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass41_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 259
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by dyshay** [comment]
Have you tried restarting the server?

**Comment by asdfxD** [comment]
yes i did, still same.

**Comment by dyshay** [comment]
I’m going to look what is wrong

I’m going back with fix soon

**Comment by asdfxD** [comment]
for every new skin i select, i have to restart the server. my ak skin works.

does this plugin have knifes included? i try karambit. i got the Karambit | Fade symbols on right, but still have the default knife.

**Comment by dyshay** [comment]
Yes this plugin has Knife included

weapon is apply on restart round

**Comment by dyshay** [comment]
You can add me on Discord: https://discord.gg/PctQUhBh

**Comment by asdfxD** [comment]
i can change the skins now ingame, but than i lost my knife and my pistol. when i respawn i got 2 ak symbols, a pistol but knife is missing.

![20240128165211_1](https://github.com/Dyshay/CS2Skin/assets/24253340/14b6080f-7fc0-4f09-9863-88316ee90d53)

when i select the other ak, i got my knife 🗡️ 

![knife](https://github.com/Dyshay/CS2Skin/assets/24253340/6d59ed60-f7e0-4b4b-8930-8e6adcc1cbd9)

**Comment by dyshay** [comment]
Add me on Discord for follow the problem 
I give update here after

**Comment by asdfxD** [comment]
still does not work for me. installed a new vanilla server + metamod 1282 + sharp 163 + skinbridge and csskin only with mysql.

database created without any issues, but when i use this example: css_skin 515 568 1 0

i got no knife/skin, i got an error in console, but data successfully added in database, when i restart the server than i get still this:

![sssssssss](https://github.com/Dyshay/CS2Skin/assets/24253340/9ded220a-3662-4eba-b616-9ca5f6f219fc)

**Comment by dyshay** [comment]
I’m going to look all issue tomorrow

**Comment by dyshay** [comment]
Can you share the error console @asdfxD here ?

**Comment by asdfxD** [comment]
i'm on debian 12 now and i can't post error logs cause skinbridge is not working in debian 12 i guess.

Metamod 1282
Sharp v164

meta list
Listing 2 plugins:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
  [02] < ERROR >

**Comment by dyshay** [comment]
"i got an error in console"

**Comment by dyshay** [comment]
Working well on ubuntu :/

**Comment by asdfxD** [comment]
y, in debian 11 before. but now i'm on deb12 and skinbridge does not work.

**Comment by asdfxD** [comment]
try ubuntu now lol, if its working there, than it wont work in debian.

**Comment by asdfxD** [comment]
20.04

meta list
Listing 2 plugins:
[01] CounterStrikeSharp (0.1.0) by Roflmuffin
[02] < ERROR >

...

**Comment by asdfxD** [comment]
its probably skinbridge never worked for me

plugins seems to be running, i got butterfly icon but have default knife, something must be wrong with skinbridge.

**Comment by dyshay** [comment]
I don't understand what the problem is. The other person who reported an error had no trouble installing the plugin.

**Comment by asdfxD** [comment]
found out what the problem is

**Comment by asdfxD** [comment]
try manually load skinbridge 

Failed to load plugin addons/SkinBridge/SkinBridge.so (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/container/game/csgo/addons/SkinBridge/SkinBridge.so)).

**Comment by asdfxD** [comment]
required to have GLIBCXX_3.4.29

**Comment by asdfxD** [comment]
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
**GLIBCXX_3.4.29**
GLIBCXX_3.4.30
GLIBCXX_DEBUG_MESSAGE_LENGTH

still does not work 

Listing 4 plugins:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
  [02] AuthSessionFix (1.0.0.0) by Poggu
  [03] ServerListPlayersFix (1.0.0.0) by Poggu
  [04] < ERROR >
meta load addons/SkinBridge/SkinBridge.so
Failed to load plugin addons/SkinBridge/SkinBridge.so (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/container/game/csgo/addons/SkinBridge/SkinBridge.so)).

i gave up.

**Comment by adrian7123** [comment]
the new cs2 update came with this problem, SkinBridge does not work now

**Comment by adrian7123** [comment]
the error happens here:
``` if (ConstantsWeapon.g_KnivesMap.ContainsKey(weaponId))
{
    Server.ExecuteCommand($"i_subclass_change {weaponInfo.DefIndex} {entity.Index}");
} 
````
I fixed it by changing it:
```
if (ConstantsWeapon.g_KnivesMap.ContainsKey(weaponId))
{
    Server.ExecuteCommand("sv_cheats 1");

    pBasePlayerWeapon.AttributeManager.Item.EntityQuality = 3;
    Server.ExecuteCommand($"subclass_change {weaponInfo.DefIndex} {entity.Index}");

    Server.ExecuteCommand("sv_cheats 0");
}
```

**Comment by asdfxD** [comment]
skinbridge update?

**Comment by asdfxD** [comment]
RIP
